version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    environment:
      POSTGRES_DB: seguranca_nodejs_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
